## Numpy and its functions

In [2]:
import numpy as np

In [3]:
emp_salary=np.random.randint(8,70,10)

In [4]:
emp_salary

array([28, 16, 27, 55, 48,  9, 24, 58, 64, 62])

In [ ]:
#set minimum and maximum salary using a_min and a_max 

In [5]:
np.clip(emp_salary,a_min=20,a_max=50)# if we use clip method then all maximum and minimum value we can set as per our use

array([28, 20, 27, 50, 48, 20, 24, 50, 50, 50])

In [ ]:
#If you want to find actual salary which are less then or greater than some salary use np.where
#np.where gives index detail

In [6]:
print(np.where(emp_salary <25))

(array([1, 5, 6], dtype=int64),)


In [ ]:
#If you want to see actual data, use index 

In [7]:
emp_salary[[1,4]]

array([16, 48])

In [9]:
print(np.where(emp_salary >25))

(array([0, 2, 3, 4, 7, 8, 9], dtype=int64),)


In [10]:
print(np.where(emp_salary >=25))

(array([0, 2, 3, 4, 7, 8, 9], dtype=int64),)


In [11]:
print(np.where(emp_salary <=25))

(array([1, 5, 6], dtype=int64),)


In [12]:
print(np.where(emp_salary ==25))


(array([], dtype=int64),)


 ### Reshaping Objects

In [14]:
import numpy as np
from numpy.random import randint as ri

In [15]:
a=ri(1,99,30)
print(a)

[71 34 83 70 73  1 33 20 17  3 62 51  1 22  6 41 83 77 71 15 56 55  3 63
 71 84 39 26 11 23]


In [16]:
b=a.reshape(2,3,5)
print(b)

[[[71 34 83 70 73]
  [ 1 33 20 17  3]
  [62 51  1 22  6]]

 [[41 83 77 71 15]
  [56 55  3 63 71]
  [84 39 26 11 23]]]


In [17]:
c=a.reshape(6,5)
print(c)

[[71 34 83 70 73]
 [ 1 33 20 17  3]
 [62 51  1 22  6]
 [41 83 77 71 15]
 [56 55  3 63 71]
 [84 39 26 11 23]]


In [18]:
print("Minimum of a is ",c.min())
print("Maximum of a is ",c.max())

Minimum of a is  1
Maximum of a is  84


## Sorting 

In [19]:
m=ri(1,100,25).reshape(5,5) #matrix of random integer
print("\n 5 X 5 matrix of random integer \n",'-'*50,'\n',m)
print("\n Here is the sorted matrix along each row \n",'-'*50,'\n',np.sort(m))#default axis=1
print("\n Here is the sorted matrix along each column \n",'-'*50,'\n',np.sort(m,axis=0))


 5 X 5 matrix of random integer 
 -------------------------------------------------- 
 [[55 25 13  6 54]
 [27 13 25 29 13]
 [ 8  3  2 46 90]
 [96  9 14 34 64]
 [90 36 19 46 61]]

 Here is the sorted matrix along each row 
 -------------------------------------------------- 
 [[ 6 13 25 54 55]
 [13 13 25 27 29]
 [ 2  3  8 46 90]
 [ 9 14 34 64 96]
 [19 36 46 61 90]]

 Here is the sorted matrix along each column 
 -------------------------------------------------- 
 [[ 8  3  2  6 13]
 [27  9 13 29 54]
 [55 13 14 34 61]
 [90 25 19 46 64]
 [96 36 25 46 90]]


 ## Index and slicing

In [20]:
arr=np.arange(13,30)
print("Array",arr)


Array [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [21]:
print("Element of 7th index is =",arr[7])

Element of 7th index is = 20


In [22]:
print("Element of 3rd and 5th index is = ",arr[3:5])

Element of 3rd and 5th index is =  [16 17]


In [23]:
print("Element up to 4th index are :",arr[4:])

Element up to 4th index are : [17 18 19 20 21 22 23 24 25 26 27 28 29]


In [ ]:
#Store arr in abc and check upto 4th index of abc

In [24]:
abc=arr[4:]
print(abc)

[17 18 19 20 21 22 23 24 25 26 27 28 29]


In [25]:
print("Element from last backwords : ",abc[-1::-2])

Element from last backwords :  [29 27 25 23 21 19 17]


In [26]:
print("7th elemets from last backword are : ",arr[-1:-8:-1])

7th elemets from last backword are :  [29 28 27 26 25 24 23]


In [27]:
print("Elements at 2nd 4th and 9th index are : ",arr[[2,4,9]])#Pass a list as a index to subset

Elements at 2nd 4th and 9th index are :  [15 17 22]


In [28]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
print("Entire row at index 2: ",mat[2])

Entire row at index 2:  [7 8 9]


In [30]:
print("Entire column at index  3:\n",mat[:,1:])

Entire column at index  3:
 [[2 3]
 [5 6]
 [8 9]]


In [31]:
print("\nSubsetting Sub-Matricss\n---------")
print("Matrics with row indices 1 and 2 and column indices 3 and 4\n",mat[1:2,1:2])


Subsetting Sub-Matricss
---------
Matrics with row indices 1 and 2 and column indices 3 and 4
 [[5]]


In [32]:
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print(mat[0:2,[1,2]])


[[2 3]
 [5 6]]


In [34]:
#Update Matrix

In [35]:
print("Original Matrix \n\n",mat)

Original Matrix 

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
mat[0,2]=200

In [38]:
mat

array([[  1,   2, 200],
       [  4,   5,   6],
       [  7,   8,   9]])

In [39]:
mat[1,0]=100

In [40]:
mat

array([[  1,   2, 200],
       [100,   5,   6],
       [  7,   8,   9]])

## Subsetting
#subsetting means when we wann to fetch only few data from matrix then we use subsetting method.

In [85]:
mat=np.array(ri(15,100,15)).reshape(3,5)
print('Matrix of random 2 digit number \n------\n',mat)

Matrix of random 2 digit number 
------
 [[34 38 29 95 17]
 [92 96 95 90 17]
 [55 37 32 17 44]]


In [86]:
print("Elements greater than 50\n ",mat[mat>50])

Elements greater than 50
  [95 92 96 95 90 55]


In [87]:
print(np.where(mat==98))

(array([], dtype=int64), array([], dtype=int64))


In [88]:
age=50
np.where(age>68,'Retired','Still Working')

array('Still Working', dtype='<U13')

## Universal Functions

In [45]:
mat1=np.array(ri(1,10,9)).reshape(3,3)
mat2=np.array(ri(1,10,9)).reshape(3,3)

print("\n 1st Matrics of Single digit number \n---------------\n",mat1)
print("\n 2st Matrics of Single digit number \n---------------\n",mat2)


 1st Matrics of Single digit number 
---------------
 [[4 1 3]
 [3 2 7]
 [1 3 9]]

 2st Matrics of Single digit number 
---------------
 [[6 6 1]
 [2 4 2]
 [6 2 6]]


In [46]:
print('mat1=\n',mat1)
print('mat2=\n',mat2)

mat1=
 [[4 1 3]
 [3 2 7]
 [1 3 9]]
mat2=
 [[6 6 1]
 [2 4 2]
 [6 2 6]]


In [47]:
print("\n Division \n---------------------\n",mat1/mat2)


 Division 
---------------------
 [[0.66666667 0.16666667 3.        ]
 [1.5        0.5        3.5       ]
 [0.16666667 1.5        1.5       ]]


In [48]:
print("\n Linear combination : 3*A - 2*B \n",3*mat1-2*mat2)


 Linear combination : 3*A - 2*B 
 [[ 0 -9  7]
 [ 5 -2 17]
 [-9  5 15]]


## Broadcasting-

#Numpy operations are usually dont on pairs of arrays on an element by element basis. in the simplest case, the two arays must have exactly the same shape
#Numpy broadcasting rules relaxex this constraints when the array shape meet certain constraints when operatings on two array,
#Numpy compares their shape element wise it starts with the trailing dimensions ,and word its way forword ,two dimension are compatible
#when they are eqaul,or one of them is 1

In [61]:
start=np.zeros((4,4))
print(start)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#create a rank1 ndarray with 3 values

In [71]:
add_rows=np.array([[1,0,2,3]])
print(add_rows)

[[1 0 2 3]]


In [72]:
y=start+add_rows 

In [73]:
y

array([[1., 0., 2., 3.],
       [1., 0., 2., 3.],
       [1., 0., 2., 3.],
       [1., 0., 2., 3.]])

In [67]:
new_row=add_rows.T 

In [68]:
new_row

array([[1],
       [0],
       [2]])

In [ ]:
test=new_row+start
print(test)

In [70]:
#craete table ndarray which is 4 X 1 to broadcast across coloumn

In [56]:
ad_cols=np.array([[0,2,2,3]])

In [57]:
ad_cols=ad_cols.T

In [58]:
ad_cols

array([[0],
       [2],
       [2],
       [3]])

## Array Math

In [60]:
mat1=np.array(ri(1,8,9)).reshape(3,3)
mat2=np.array(ri(1,8,9)).reshape(3,3)

print("\n 1st Matrix of random single digit number\n---------------------------\n",mat1)
print("\n 2nd Matrix of random single digit number\n---------------------------\n",mat2)

print("\n sq-root of 1st Matrix using np\n",'-'*50,"\n",np.sqrt(mat1))
print("\n square of 2nd Matrix using np\n",'-'*50,"\n",np.square(mat2))


 1st Matrix of random single digit number
---------------------------
 [[5 3 1]
 [3 3 1]
 [5 2 5]]

 2nd Matrix of random single digit number
---------------------------
 [[4 7 5]
 [7 1 1]
 [7 6 2]]

 sq-root of 1st Matrix using np
 -------------------------------------------------- 
 [[2.23606798 1.73205081 1.        ]
 [1.73205081 1.73205081 1.        ]
 [2.23606798 1.41421356 2.23606798]]

 square of 2nd Matrix using np
 -------------------------------------------------- 
 [[16 49 25]
 [49  1  1]
 [49 36  4]]
